### ISSUE TITLE
Projects management

### ISSUE THREAD

**Issue by Michael-Jk** [leandersteiner/mauw-ss2023#4]
AC:

- Create / Edit / Delete Projects
- Overview of all projects of user
- Ability to add other users to a project

## Tasks

- [x] https://github.com/leandersteiner/mauw-ss2023/issues/5

- [x] https://github.com/leandersteiner/mauw-ss2023/issues/6

- [x] https://github.com/leandersteiner/mauw-ss2023/issues/7
